maintainer       "YOUR_COMPANY_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures mongodb"
version          "0.0.1"
supports "ubuntu"
depends "build-essential"
# depends "boost"
